version: '3'
services:
  app:
    build: .
    depends_on:
      - mosquitto
    links:
      - mosquitto
    environment:
      DEBUG_MODE: "true"
      BOT_TOKEN: "${BOT_TOKEN}"
      ALLOWED_TELEGRAM_IDS: "${ALLOWED_TELEGRAM_IDS}"
      MQTT_BROKER_HOST: "${MQTT_BROKER_HOST}"
  mosquitto:
    image: eclipse-mosquitto:1.6
    volumes:
    - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
